name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow when a tag starting with 'v' is pushed
      
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Set the tag name as an environment variable for later use
      # Create a zip file of the repository
      - name: Zip the repository contents
        run: |
          zip -r "publish/RCLootCouncil_AddRollAlert-${{ env.TAG_NAME }}.zip" . -x "*.git/*" -x ".vscode/*" -x ".github/**/*"
      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      # Attach zip to release 
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: publish/RCLootCouncil_AddRollAlert-${{ env.TAG_NAME }}.zip
          asset_name: RCLootCouncil_AddRollAlert-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip