name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow when a tag starting with 'v' is pushed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Extract the version number from the .toc file
      - name: Extract version from .toc
        id: extract_version
        run: |
          VERSION=$(grep -m 1 '^## Version:' RCLootCouncil_AddRollAlert.toc | awk -F ': ' '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Step 3: Create a zip file of the repository
      - name: Zip the repository contents
        run: |
          zip -r "${GITHUB_WORKSPACE}/RCLootCouncil_AddRollAlert-${{ env.VERSION }}.zip" .

      # Step 4: Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${GITHUB_WORKSPACE}/RCLootCouncil_AddRollAlert-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}